version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: fitbuddy_postgres
    environment:
      POSTGRES_USER: fitbuddy_user
      POSTGRES_PASSWORD: fitbuddy_password
      POSTGRES_DB: fitbuddy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: fitbuddy_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  postgres_data:
